@BLOG_ID=670f7f03667b6ddaee44240d
@BASE_API_URL=localhost:3003/api

@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMiIsImlkIjoiNjcxYWNlY2U3YTk5Y2NlZTRkZjIwYTVmIiwiaWF0IjoxNzI5ODEzMDU3fQ.BXjlsetEiL4S7Qx-UYtqj3gL5vVosZyN2tE4hvzx6f0

### USERS
GET http://{{BASE_API_URL}}/users
Authorization: Bearer {{TOKEN}}

###
POST http://{{BASE_API_URL}}/users
Content-Type: application/json

{
    "username": "johndoe{{$randomInt 1 100}}",
    "name": "John Doe",
    // "password": "password{{$randomInt 1 100}}"
    "password": "passwordtest"
}

### AUTH
POST http://{{BASE_API_URL}}/login
Content-Type: application/json

{
    "username": "johndoe50",
    "password": "passwordtest"
}

### BLOGS
GET http://{{BASE_API_URL}}/blogs

###
POST http://{{BASE_API_URL}}/blogs
Content-Type: application/json

{
    "title": "My {{$randomInt 1 100}}th blog",
    "author": "John Doe {{$randomInt 1 100}}",
    "url": "http://www.johndoe.com",
    "likes": "{{$randomInt 1 100}}",
    "user": "671ac1ee0b4ada3c76b13d64"
}

###
DELETE http://{{BASE_API_URL}}/blogs/{{BLOG_ID}}
